### ISSUE TITLE
Running in Intellij

### ISSUE THREAD

**Issue by leoprince** [odrotbohm/spring-restbucks#109]
I am able to run spring-restbucks from command line using  https://github.com/odrotbohm/spring-restbucks#quickstart
However while running in intellij, getting below error.
Any preferences needs to included for Intellij - Thanks!

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'drinksOptions' defined in file [/Users/leo/dev/spring-restbucks/server/target/classes/org/springsource/restbucks/drinks/DrinksOptions.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'drinks' defined in org.springsource.restbucks.drinks.Drinks defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Not a managed type: class org.springsource.restbucks.drinks.Drink
`

**Comment by johannschenkl** [comment]
@leoprince same issue here, how did you solve it? Thanks a lot!
