### ISSUE TITLE
CreditCardPayment contains CreditCard

### ISSUE THREAD

**Issue by OLibutzki** [odrotbohm/spring-restbucks#113]
While inspecting the result of the docs generated by archifacts (https://archifacts.github.io/spring-restbucks-example/) I stumbled upon the aggregate root `CreditCardPayment` which contains another aggregate root `CreditCard`.

Is this intended? Aggregate roots should only be referenced by there id and should not be nested in another aggregate root, right? I would expect that `CreditCardPayment` references `CreditCard` by using `CreditCardNumber`.

**Comment by odrotbohm** [comment]
Good catch! That has been fixed with d743cebca9b9e20561a4351cf5d7ec4a32327975.
